### ISSUE TITLE
Conversion error even after policy.xml is changed as per README

### ISSUE THREAD

**Issue by krishnakumarg1984** [ashafaei/pdf2pptx#5]
Hi,

I have changed the policy.xml as suggested in your README. I get the following error message

> pdf2pptx: line 33: 25392 Aborted                 (core dumped) convert -density $density $colorspace -resize "x${resolution}" $1 ./$tempname/slide.png
Error with extraction

How can I workaround this issue?

JFYI, the following is the output of imagemagick version query:
```
$ convert --version
Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib
```

**Comment by ashafaei** [comment]
Hi @krishnakumarg1984 ,
Can you try the script with the provided `pdf` example and let me know how it goes?
It appears that convert is crashing. Knowing whether it works with the provided demo pdf would help us narrow down the problem.
